
package chapinmarket.frontend.vistas;

import chapinmarket.backend.controladores.ControlExistencia;
import chapinmarket.backend.enums.CommSQL;
import chapinmarket.backend.modelos.Empleado;
import chapinmarket.backend.modelos.Existencia;
import chapinmarket.backend.modelos.Producto;
import chapinmarket.frontend.paneles.PanelDegradado;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CIROSS
 */
public class VistaInventario extends javax.swing.JFrame {

    private Empleado empleado;
    private static CommSQL instruccion;
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    
    /**
     * Creates new form VistaInventario
     */
    public VistaInventario() {
        initComponents();
        setLocationRelativeTo(null);
        this.jPanelDatos.setVisible(false);
        this.jPanelTraslado.setVisible(false);
        pack();
    }

    public VistaInventario(Empleado empleado) {
        this();
        this.empleado = empleado;
        jLabelUsuario.setText(empleado.getNombre()+" "+empleado.getApellido());
        jLabelSucursal.setText(empleado.getSucursal().getNombre());
        inicializarTabla();
        llenarTabla();
    }

    public void inicializarTabla() {
        
        modeloTabla.addColumn("Codigo");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Marca");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Cantidad Bodega");
        modeloTabla.addColumn("Cantidad Estante");
        modeloTabla.addColumn("Número Pasillo");
        modeloTabla.addColumn("Descripcion");

        this.jTable.setModel(modeloTabla);
    }

    public void llenarTabla() {
        ControlExistencia.mostrarRegistros(modeloTabla, empleado, true);
    }
    
    public void actualizarTabla() {
        int filas = modeloTabla.getRowCount();
        for (int i = 0; i < filas; i++) {
            modeloTabla.removeRow(0);
        }
        llenarTabla();
    }
    
    public Object getDatos() {
        String codigo = jTextFieldCodigoProducto.getText();
        int cantidad = Integer.parseInt(jTextFieldCantidadTraslado.getText());
        int pasillo = Integer.parseInt(jTextFieldNumeroPasillo.getText());
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo1 = new javax.swing.JLabel();
        jPanelFondo = new javax.swing.JPanel();
        jPanelHeader = new PanelDegradado(new java.awt.Color(102, 0, 102,200),new java.awt.Color(204, 102, 255,125));
        jLabelUsuario = new javax.swing.JLabel();
        jLabelRol = new javax.swing.JLabel();
        jLabelSucursal = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldCodigoBarras = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldCantidadBodega = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        jButtonoOcultar = new javax.swing.JButton();
        jPanelListaProductos = new javax.swing.JPanel();
        jLabelListaProductos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonConsultarProducto = new javax.swing.JButton();
        jButtonTrasladarProducto = new javax.swing.JButton();
        jPanelTraslado = new javax.swing.JPanel();
        jLabelTituloTraslado = new javax.swing.JLabel();
        jTextFieldCodigoProducto = new javax.swing.JTextField();
        jTextFieldCantidadTraslado = new javax.swing.JTextField();
        jTextFieldNumeroPasillo = new javax.swing.JTextField();
        jButtonRealizarTraslado = new javax.swing.JButton();
        jButtonCancelarTraslado = new javax.swing.JButton();

        jLabelTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setText("TRASLADAR PRODUCTOS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelUsuario.setText("(nombre usuario)");

        jLabelRol.setBackground(new java.awt.Color(51, 51, 51));
        jLabelRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRol.setText("ENCARGADO DE INVENTARIO");

        jLabelSucursal.setBackground(new java.awt.Color(51, 51, 51));
        jLabelSucursal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSucursal.setText("(sucursal)");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelRol)
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSucursal, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSucursal)
                .addGap(21, 21, 21))
        );

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTitulo.setText("Datos de Producto:");

        jTextFieldCodigoBarras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodigoBarras.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Código de Barras:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Nombre:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jTextFieldMarca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMarca.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Marca:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jTextFieldPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecio.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Precio:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jTextFieldCantidadBodega.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCantidadBodega.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Cantidad en Bodega:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Descripción:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setLineWrap(true);
        jTextAreaDescripcion.setRows(5);
        jTextAreaDescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaDescripcion);

        jButtonoOcultar.setBackground(new java.awt.Color(0, 153, 51));
        jButtonoOcultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonoOcultar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonoOcultar.setText("Ocultar");
        jButtonoOcultar.setActionCommand("");
        jButtonoOcultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonoOcultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextFieldCantidadBodega, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jTextFieldCodigoBarras, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonoOcultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCantidadBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonoOcultar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelListaProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelListaProductos.setForeground(new java.awt.Color(51, 51, 51));
        jLabelListaProductos.setText("Lista de Productos");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Marca", "Precio", "Cantidad Bodega", "Cantidad Estantes", "Numero Pasillo", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable);

        jButtonConsultarProducto.setBackground(new java.awt.Color(0, 153, 153));
        jButtonConsultarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonConsultarProducto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarProducto.setText("Consultar Producto");
        jButtonConsultarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarProductoActionPerformed(evt);
            }
        });

        jButtonTrasladarProducto.setBackground(new java.awt.Color(0, 153, 204));
        jButtonTrasladarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonTrasladarProducto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTrasladarProducto.setText("Trasladar Producto");
        jButtonTrasladarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrasladarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListaProductosLayout = new javax.swing.GroupLayout(jPanelListaProductos);
        jPanelListaProductos.setLayout(jPanelListaProductosLayout);
        jPanelListaProductosLayout.setHorizontalGroup(
            jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                        .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelListaProductos)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButtonTrasladarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConsultarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );
        jPanelListaProductosLayout.setVerticalGroup(
            jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaProductosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelListaProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTrasladarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabelTituloTraslado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTituloTraslado.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTituloTraslado.setText("Traslado de Producto:");

        jTextFieldCodigoProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodigoProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Código de Producto:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jTextFieldCantidadTraslado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCantidadTraslado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Cantidad a Trasladar:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jTextFieldNumeroPasillo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNumeroPasillo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Número de Pasillo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jButtonRealizarTraslado.setBackground(new java.awt.Color(0, 153, 51));
        jButtonRealizarTraslado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonRealizarTraslado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRealizarTraslado.setText("Trasladar");
        jButtonRealizarTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarTrasladoActionPerformed(evt);
            }
        });

        jButtonCancelarTraslado.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCancelarTraslado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCancelarTraslado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelarTraslado.setText("Cancelar");
        jButtonCancelarTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarTrasladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTrasladoLayout = new javax.swing.GroupLayout(jPanelTraslado);
        jPanelTraslado.setLayout(jPanelTrasladoLayout);
        jPanelTrasladoLayout.setHorizontalGroup(
            jPanelTrasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrasladoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelTrasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldNumeroPasillo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCantidadTraslado, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloTraslado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jTextFieldCodigoProducto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRealizarTraslado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelarTraslado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelTrasladoLayout.setVerticalGroup(
            jPanelTrasladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrasladoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelTituloTraslado)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldCantidadTraslado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNumeroPasillo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRealizarTraslado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelarTraslado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTraslado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTraslado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarProductoActionPerformed
        
        String codigo = JOptionPane.showInputDialog("Ingrese el codigo del producto:");
        habilitarPanelDatos(true);
        
        if (codigo != null) {
            //Producto producto = ControlProducto.getProductoPorCodigo(codigo);
            Existencia existencia = ControlExistencia.getExistenciaPorIDS(codigo, empleado.getSucursal().getId());
            if (existencia==null) {
                JOptionPane.showMessageDialog(null, "No se encontró el producto con el código ingresado","Codigo incorrecto",JOptionPane.ERROR_MESSAGE);
                habilitarPanelDatos(false);
            } else {
                llenarCamposDatos(existencia.getProducto(), existencia.getCantidadBodega());
            }
        } else {
            habilitarPanelDatos(false);
        }
    }//GEN-LAST:event_jButtonConsultarProductoActionPerformed

    private void jButtonTrasladarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrasladarProductoActionPerformed
        habilitarPanelTraslado(true);
        this.pack();
    }//GEN-LAST:event_jButtonTrasladarProductoActionPerformed

    private void jButtonoOcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonoOcultarActionPerformed
        habilitarPanelDatos(false);
        llenarCamposDatos(new Producto("","","",0), 0);
        this.pack();
    }//GEN-LAST:event_jButtonoOcultarActionPerformed

    private void jButtonRealizarTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarTrasladoActionPerformed
        String codigo = jTextFieldCodigoProducto.getText();
        int cantidad = Integer.parseInt(jTextFieldCantidadTraslado.getText());
        System.out.println("cantidad="+cantidad);
        int pasillo = Integer.parseInt(jTextFieldNumeroPasillo.getText());
        System.out.println("pasillo="+pasillo);
        Existencia existencia = ControlExistencia.getExistenciaPorIDS(codigo, empleado.getSucursal().getId());
        System.out.println(existencia.toString());
        
        if (existencia == null) {
            JOptionPane.showMessageDialog(null, "No se encontró el producto con el código ingresado","Codigo incorrecto",JOptionPane.ERROR_MESSAGE);
        } else if (existencia.getCantidadBodega() < cantidad) {
            JOptionPane.showMessageDialog(null, "Los productos en bodega no son suficientes para la cantidad solicitada","Cantidad excedida",JOptionPane.ERROR_MESSAGE);
        } else {
            int nuevoestante = existencia.getCantidadEstante() + cantidad;
            existencia.setCantidadEstante(nuevoestante);
            existencia.setCantidadBodega(existencia.getCantidadBodega() - cantidad);
            existencia.setNumeroPasillo(pasillo);
            
            ControlExistencia.ejecutarInstruccionPSQL(CommSQL.UPDATE, existencia);
            actualizarTabla();
            habilitarPanelTraslado(false);
            limpiarCamposTraslado();
            this.pack();
        }
        
    }//GEN-LAST:event_jButtonRealizarTrasladoActionPerformed

    private void limpiarCamposTraslado() {
        jTextFieldCodigoProducto.setText("");
        jTextFieldCantidadTraslado.setText("");
        jTextFieldNumeroPasillo.setText("");
    }
    
    private void jButtonCancelarTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarTrasladoActionPerformed
        limpiarCamposTraslado();
        habilitarPanelTraslado(false);
        this.pack();
    }//GEN-LAST:event_jButtonCancelarTrasladoActionPerformed
    
    private void llenarCamposDatos(Producto producto, int cantidadBodega) {
        jTextFieldCodigoBarras.setText(producto.getCodigo());
        jTextFieldCodigoBarras.setEditable(false);
        jTextFieldNombre.setText(producto.getNombre());
        jTextFieldNombre.setEditable(false);
        jTextFieldMarca.setText(producto.getMarca());
        jTextFieldMarca.setEditable(false);
        jTextAreaDescripcion.setText(producto.getDescripcion());
        jTextAreaDescripcion.setEditable(false);
        
        jTextFieldPrecio.setText(String.valueOf(producto.getPrecio()));
        jTextFieldPrecio.setEditable(false);
        jTextFieldCantidadBodega.setText(String.valueOf(cantidadBodega));
        jTextFieldCantidadBodega.setEditable(false);
    }
    
    
    
    private void habilitarPanelDatos(boolean habilitar) {
        this.jPanelDatos.setVisible(habilitar);
        this.jButtonConsultarProducto.setEnabled(!habilitar);
        this.pack();
    }
    
    private void habilitarPanelTraslado(boolean habilitar) {
        this.jPanelTraslado.setVisible(habilitar);
        this.jButtonRealizarTraslado.setEnabled(habilitar);
        this.jButtonTrasladarProducto.setEnabled(!habilitar);
        this.pack();
    }
    
    public Empleado getEmpleado() {
        return empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarTraslado;
    private javax.swing.JButton jButtonConsultarProducto;
    private javax.swing.JButton jButtonRealizarTraslado;
    private javax.swing.JButton jButtonTrasladarProducto;
    private javax.swing.JButton jButtonoOcultar;
    private javax.swing.JLabel jLabelListaProductos;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelSucursal;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTituloTraslado;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelListaProductos;
    private javax.swing.JPanel jPanelTraslado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextFieldCantidadBodega;
    private javax.swing.JTextField jTextFieldCantidadTraslado;
    private javax.swing.JTextField jTextFieldCodigoBarras;
    private javax.swing.JTextField jTextFieldCodigoProducto;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroPasillo;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
