
package chapinmarket.frontend.vistas;

import chapinmarket.backend.controladores.ControlCliente;
import chapinmarket.backend.controladores.ControlExistencia;
import chapinmarket.backend.controladores.ControlFactura;
import chapinmarket.backend.controladores.ControlVenta;
import chapinmarket.backend.modelos.Cliente;
import chapinmarket.backend.modelos.Empleado;
import chapinmarket.backend.modelos.Factura;
import chapinmarket.backend.modelos.Venta;
import chapinmarket.frontend.paneles.PanelDatosCliente;
import chapinmarket.frontend.paneles.PanelDegradado;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CIROSS
 */
public class VistaCajero extends javax.swing.JFrame {

    private Empleado empleado;
    private Cliente cliente;
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private String fechaTxt;
    
    private Factura facturaActual;
    private ArrayList<Venta> listaVentas = new ArrayList<>();
    
    /**
     * Creates new form VistaCajero
     */
    public VistaCajero() {
        initComponents();
        setLocationRelativeTo(null);
        cambiarEstadoVenta(true);
    }

    public VistaCajero(Empleado empleado) {
        this();
        this.empleado = empleado;
        jLabelCajero.setText("Atiende: "+empleado.getNombre()+" "+empleado.getApellido());
        this.fechaTxt = new SimpleDateFormat("yyyy/MM/dd").format(Calendar.getInstance().getTime());
        jLabelFecha.setText("Fecha: "+fechaTxt);
        inicializarTabla();
        
    }
    
    public void inicializarTabla() {
        
        modeloTabla.addColumn("Codigo");
        modeloTabla.addColumn("Producto");
        modeloTabla.addColumn("Marca");
        modeloTabla.addColumn("Descripcion");
        modeloTabla.addColumn("Precio");

        this.jTableArticulos.setModel(modeloTabla);
    }

    public void llenarTabla() {
        ControlVenta.mostrarRegistros(modeloTabla, empleado);
    }
    
    public void actualizarTabla() {
        int filas = modeloTabla.getRowCount();
        for (int i = 0; i < filas; i++) {
            modeloTabla.removeRow(0);
        }
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEncabezado = new javax.swing.JPanel();
        jLabelCajero = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelNit = new javax.swing.JLabel();
        jPanelTotalPagar = new javax.swing.JPanel();
        jLabelTituloPagar = new javax.swing.JLabel();
        jLabelCantidadTPagar = new javax.swing.JLabel();
        jPanelTotalDescuento = new javax.swing.JPanel();
        jLabelTituloDescuento = new javax.swing.JLabel();
        jLabelCantidadTDescuento = new javax.swing.JLabel();
        jPanelInputs = new javax.swing.JPanel();
        jButtonAgregarProducto = new javax.swing.JButton();
        jLabelCodigoProducto = new javax.swing.JLabel();
        jTextFieldCodigoProducto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelNuevaVenta = new PanelDegradado(new java.awt.Color(0,150,200,100),new java.awt.Color(150,250,200,75));
        jButtonEditarCliente = new javax.swing.JButton();
        jButtonIniciarVenta = new javax.swing.JButton();
        jTextFieldNitCliente = new javax.swing.JTextField();
        jLabelNitCliente = new javax.swing.JLabel();
        jLabelNuevaVenta = new javax.swing.JLabel();
        jPanelListadoProductos = new javax.swing.JPanel();
        jButtonCancelarCompra = new javax.swing.JButton();
        jButtonFinalizarCompra = new javax.swing.JButton();
        jLabelNumeroFactura = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArticulos = new javax.swing.JTable();
        jLabelFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelEncabezado.setBackground(new java.awt.Color(0, 153, 204));

        jLabelCajero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCajero.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCajero.setText("Atiende:");

        jLabelCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCliente.setForeground(new java.awt.Color(51, 51, 51));
        jLabelCliente.setText("Cliente:");

        jLabelNit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelNit.setForeground(new java.awt.Color(51, 51, 51));
        jLabelNit.setText("NIT:");

        jLabelTituloPagar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelTituloPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloPagar.setText("TOTAL A PAGAR:");

        jLabelCantidadTPagar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelCantidadTPagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCantidadTPagar.setText(" ");

        javax.swing.GroupLayout jPanelTotalPagarLayout = new javax.swing.GroupLayout(jPanelTotalPagar);
        jPanelTotalPagar.setLayout(jPanelTotalPagarLayout);
        jPanelTotalPagarLayout.setHorizontalGroup(
            jPanelTotalPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalPagarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelTotalPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTituloPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jLabelCantidadTPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelTotalPagarLayout.setVerticalGroup(
            jPanelTotalPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalPagarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelTituloPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCantidadTPagar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelTituloDescuento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelTituloDescuento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloDescuento.setText("TOTAL CON DESCUENTO:");

        jLabelCantidadTDescuento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelCantidadTDescuento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelTotalDescuentoLayout = new javax.swing.GroupLayout(jPanelTotalDescuento);
        jPanelTotalDescuento.setLayout(jPanelTotalDescuentoLayout);
        jPanelTotalDescuentoLayout.setHorizontalGroup(
            jPanelTotalDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTotalDescuentoLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanelTotalDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTituloDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCantidadTDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanelTotalDescuentoLayout.setVerticalGroup(
            jPanelTotalDescuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalDescuentoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelTituloDescuento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCantidadTDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelEncabezadoLayout = new javax.swing.GroupLayout(jPanelEncabezado);
        jPanelEncabezado.setLayout(jPanelEncabezadoLayout);
        jPanelEncabezadoLayout.setHorizontalGroup(
            jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNit)
                    .addComponent(jLabelCliente)
                    .addComponent(jLabelCajero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTotalDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanelEncabezadoLayout.setVerticalGroup(
            jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEncabezadoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelTotalPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelEncabezadoLayout.createSequentialGroup()
                        .addComponent(jLabelCajero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNit))
                    .addComponent(jPanelTotalDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButtonAgregarProducto.setBackground(new java.awt.Color(0, 153, 204));
        jButtonAgregarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarProducto.setText("Agregar");
        jButtonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarProductoActionPerformed(evt);
            }
        });

        jLabelCodigoProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCodigoProducto.setText("Código de Producto:");

        jButtonEditarCliente.setBackground(new java.awt.Color(0, 204, 102));
        jButtonEditarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarCliente.setText("Editar Cliente");
        jButtonEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarClienteActionPerformed(evt);
            }
        });

        jButtonIniciarVenta.setBackground(new java.awt.Color(0, 204, 153));
        jButtonIniciarVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonIniciarVenta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciarVenta.setText("Iniciar Venta");
        jButtonIniciarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarVentaActionPerformed(evt);
            }
        });

        jLabelNitCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNitCliente.setText("NIT del Cliente:");

        jLabelNuevaVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNuevaVenta.setForeground(new java.awt.Color(0, 102, 153));
        jLabelNuevaVenta.setText("NUEVA VENTA");

        javax.swing.GroupLayout jPanelNuevaVentaLayout = new javax.swing.GroupLayout(jPanelNuevaVenta);
        jPanelNuevaVenta.setLayout(jPanelNuevaVentaLayout);
        jPanelNuevaVentaLayout.setHorizontalGroup(
            jPanelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNuevaVentaLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonEditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonIniciarVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNitCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(jPanelNuevaVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNuevaVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNuevaVentaLayout.setVerticalGroup(
            jPanelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNuevaVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNuevaVenta)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabelNitCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonIniciarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanelInputsLayout = new javax.swing.GroupLayout(jPanelInputs);
        jPanelInputs.setLayout(jPanelInputsLayout);
        jPanelInputsLayout.setHorizontalGroup(
            jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInputsLayout.createSequentialGroup()
                .addGroup(jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelInputsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInputsLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelNuevaVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelInputsLayout.createSequentialGroup()
                                .addComponent(jLabelCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldCodigoProducto, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(25, 25, 25))
        );
        jPanelInputsLayout.setVerticalGroup(
            jPanelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInputsLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelCodigoProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCancelarCompra.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCancelarCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCancelarCompra.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelarCompra.setText("Cancelar");

        jButtonFinalizarCompra.setBackground(new java.awt.Color(0, 153, 51));
        jButtonFinalizarCompra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonFinalizarCompra.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFinalizarCompra.setText("Finalizar Compra");
        jButtonFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarCompraActionPerformed(evt);
            }
        });

        jLabelNumeroFactura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNumeroFactura.setText("Factura No.: ");

        jTableArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Marca", "Descripción", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableArticulos);

        jLabelFecha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFecha.setText("Fecha:          ");

        javax.swing.GroupLayout jPanelListadoProductosLayout = new javax.swing.GroupLayout(jPanelListadoProductos);
        jPanelListadoProductos.setLayout(jPanelListadoProductosLayout);
        jPanelListadoProductosLayout.setHorizontalGroup(
            jPanelListadoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoProductosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelListadoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListadoProductosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListadoProductosLayout.createSequentialGroup()
                        .addComponent(jLabelNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        jPanelListadoProductosLayout.setVerticalGroup(
            jPanelListadoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoProductosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelListadoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroFactura)
                    .addComponent(jLabelFecha))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanelListadoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelListadoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelListadoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //static boolean iniciarNuevaVenta = true;
    private void jButtonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarProductoActionPerformed
        //cambiarEstadoVenta(true);
    }//GEN-LAST:event_jButtonAgregarProductoActionPerformed

    private void jButtonEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarClienteActionPerformed
        //cambiarEstadoVenta(false);
        
    }//GEN-LAST:event_jButtonEditarClienteActionPerformed

    private void cambiarEstadoVenta(boolean iniciarNuevaVenta) {
        jLabelCodigoProducto.setEnabled(!iniciarNuevaVenta);
        jTextFieldNitCliente.setEnabled(!iniciarNuevaVenta);
        jButtonAgregarProducto.setEnabled(!iniciarNuevaVenta);
        jTextFieldCodigoProducto.setEnabled(!iniciarNuevaVenta);
        jPanelNuevaVenta.setVisible(iniciarNuevaVenta);
        pack();
    }
    private void jButtonIniciarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarVentaActionPerformed
        String nit = jTextFieldNitCliente.getText();
        this.cliente = ControlCliente.getClientePorNit(nit);
        PanelDatosCliente panel = new PanelDatosCliente();
        
        String noFactura = ""+ControlFactura.getNumeroUltimaFactura()+1;
        jLabelNumeroFactura.setText("Factura No.: " + noFactura);
        
        if (cliente != null) {
            cambiarEstadoVenta(false);
        } else {
            int
        }
        
        
    }//GEN-LAST:event_jButtonIniciarVentaActionPerformed

    private void jButtonFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarCompraActionPerformed
        cambiarEstadoVenta(true);
    }//GEN-LAST:event_jButtonFinalizarCompraActionPerformed


    public Empleado getEmpleado() {
        return empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarProducto;
    private javax.swing.JButton jButtonCancelarCompra;
    private javax.swing.JButton jButtonEditarCliente;
    private javax.swing.JButton jButtonFinalizarCompra;
    private javax.swing.JButton jButtonIniciarVenta;
    private javax.swing.JLabel jLabelCajero;
    private javax.swing.JLabel jLabelCantidadTDescuento;
    private javax.swing.JLabel jLabelCantidadTPagar;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelCodigoProducto;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNit;
    private javax.swing.JLabel jLabelNitCliente;
    private javax.swing.JLabel jLabelNuevaVenta;
    private javax.swing.JLabel jLabelNumeroFactura;
    private javax.swing.JLabel jLabelTituloDescuento;
    private javax.swing.JLabel jLabelTituloPagar;
    private javax.swing.JPanel jPanelEncabezado;
    private javax.swing.JPanel jPanelInputs;
    private javax.swing.JPanel jPanelListadoProductos;
    private javax.swing.JPanel jPanelNuevaVenta;
    private javax.swing.JPanel jPanelTotalDescuento;
    private javax.swing.JPanel jPanelTotalPagar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableArticulos;
    private javax.swing.JTextField jTextFieldCodigoProducto;
    private javax.swing.JTextField jTextFieldNitCliente;
    // End of variables declaration//GEN-END:variables
}
