
package chapinmarket.frontend.vistas;

import chapinmarket.backend.controladores.ControlEmpleado;
import chapinmarket.backend.controladores.ControlSucursal;
import chapinmarket.backend.enums.CommSQL;
import chapinmarket.backend.enums.Rol;
import chapinmarket.backend.modelos.Empleado;
import chapinmarket.backend.modelos.Sucursal;
import chapinmarket.frontend.paneles.PanelDegradado;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CIROSS
 */
public class VistaAdministrador extends javax.swing.JFrame {

    private Empleado empleado;
    private static CommSQL instruccion;
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private ArrayList<Sucursal> listaSucursales;
    private Rol[] listaRoles;
    
    /**
     * Creates new form VistaAdministrador
     */
    public VistaAdministrador() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public VistaAdministrador(Empleado empleado) {
        this();
        this.empleado = empleado;
        jLabelUsuario.setText(empleado.getNombre()+" "+empleado.getApellido());
        listaSucursales = new ControlSucursal().generarListaSucursales();
        listaRoles = Rol.values();
        inicializarTabla();
        llenarTabla();
        inicializarCombos();
    }
    
    private void inicializarCombos() {
        this.jComboBoxSucursal.addItem("");
        for (int i = 0; i < listaSucursales.size(); i++) {
            this.jComboBoxSucursal.addItem(listaSucursales.get(i).getNombre());
        }
        
        for (int i = 0; i < listaRoles.length; i++) {
            this.jComboBoxRol.addItem(listaRoles[i].name());
        }
    }
    
    public void inicializarTabla() {
        
        modeloTabla.addColumn("Usuario");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Rol");
        modeloTabla.addColumn("Sucursal");
        modeloTabla.addColumn("CUI");
        modeloTabla.addColumn("Salario");
        modeloTabla.addColumn("Numero Caja");

        this.jTable.setModel(modeloTabla);
    }

    public void llenarTabla() {
        ControlEmpleado.mostrarRegistros(modeloTabla);
    }
    
    public void actualizarTabla() {
        int filas = modeloTabla.getRowCount();
        for (int i = 0; i < filas; i++) {
            modeloTabla.removeRow(0);
        }
        llenarTabla();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelHeader = new PanelDegradado(new java.awt.Color(220,140,30),new java.awt.Color(230,203,10));
        jLabelUsuario = new javax.swing.JLabel();
        jLabelRol = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelDatosEmpleado = new chapinmarket.frontend.paneles.PanelDatosCliente();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldCui = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jTextFieldNumeroCaja = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jComboBoxSucursal = new javax.swing.JComboBox<>();
        jTextFieldContrasena = new javax.swing.JTextField();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jTextFieldSalario = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonIngresar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelUsuario.setText("(nombre usuario)");

        jLabelRol.setBackground(new java.awt.Color(51, 51, 51));
        jLabelRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelRol.setText("ADMINISTRADOR");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelRol)
                    .addComponent(jLabelUsuario))
                .addGap(65, 65, 65))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRol)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 204, 0));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jTextFieldApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldApellido.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Apellido:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jTextFieldCui.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCui.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "CUI:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Datos de Empleado:");

        jTextFieldNumeroCaja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNumeroCaja.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Número de Caja:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jTextFieldUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Usuario:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jComboBoxSucursal.setBorder(javax.swing.BorderFactory.createTitledBorder("Sucursal"));

        jTextFieldContrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldContrasena.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Contraseña:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jComboBoxRol.setBorder(javax.swing.BorderFactory.createTitledBorder("Rol"));

        jTextFieldSalario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSalario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Salario:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Nombre:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jButtonGuardar.setBackground(new java.awt.Color(0, 153, 51));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 51, 51));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(0, 153, 204));
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonIngresar.setBackground(new java.awt.Color(0, 153, 204));
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosEmpleadoLayout = new javax.swing.GroupLayout(jPanelDatosEmpleado);
        jPanelDatosEmpleado.setLayout(jPanelDatosEmpleadoLayout);
        jPanelDatosEmpleadoLayout.setHorizontalGroup(
            jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                        .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldCui, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNumeroCaja)
                                .addComponent(jComboBoxRol, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE))
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                                .addComponent(jButtonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldApellido)
                                .addComponent(jTextFieldContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                .addComponent(jTextFieldSalario)
                                .addComponent(jComboBoxSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanelDatosEmpleadoLayout.setVerticalGroup(
            jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosEmpleadoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelTitulo)
                .addGap(30, 30, 30)
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNumeroCaja)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanelDatosEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingresar Empleado", jPanelDatosEmpleado);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Lista de Empleados:");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Nombre", "Apellido", "Rol", "Sucursal", "CUI", "Salario", "Numero Caja"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de Empleados", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Gestion Tarjetas", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reportes", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limpiarCamposIngresoEmpleados();
        jButtonCancelar.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        instruccion = CommSQL.UPDATE;
        String user = JOptionPane.showInputDialog("Ingrese el usuario del empleado:");
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        habilitarPanerEdicionEmpleado(true);
        
        if (user != null) {
            
            Empleado nuevoEmpleado = ControlEmpleado.obtenerEmpleadoPorId(user);
            if (nuevoEmpleado==null) {
                JOptionPane.showMessageDialog(null, "No se encontró el empleado con el usuario ingresado","Usuario incorrecto",JOptionPane.ERROR_MESSAGE);
                jButtonEditar.setEnabled(true);
                jButtonCancelar.setEnabled(false);
                habilitarPanerEdicionEmpleado(false);

            } else {
                llenarCampos(nuevoEmpleado);
                jButtonEditar.setEnabled(false);
                jButtonCancelar.setEnabled(true);
                habilitarPanerEdicionEmpleado(true);

            }
        } else {
            jButtonEditar.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            habilitarPanerEdicionEmpleado(false);
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private Empleado getDatos() {
        try {
            Empleado emp = null;
            String usuario = jTextFieldUsuario.getText();
            String contrasena = jTextFieldContrasena.getText();
            String nombre = jTextFieldNombre.getText();
            String apellido = jTextFieldApellido.getText();
            String cui = jTextFieldCui.getText();
            double salario = Double.parseDouble(jTextFieldSalario.getText());
            Rol rol = listaRoles[jComboBoxRol.getSelectedIndex()];
            
            if (rol.equals(Rol.ADMINISTRADOR)) {
                emp = new Empleado(usuario,contrasena,cui,rol,nombre,apellido,salario);
            } else {
                int indexEst = jComboBoxSucursal.getSelectedIndex()-1;
                Sucursal sucursal = listaSucursales.get(indexEst);
                if (rol.equals(Rol.CAJERO)) {
                    int numeroCaja = Integer.parseInt(jTextFieldNumeroCaja.getText());
                    emp = new Empleado(usuario, contrasena, cui, rol, sucursal, nombre, apellido, salario, numeroCaja);
                } else {
                    emp = new Empleado(usuario, contrasena, cui, rol, sucursal, nombre, apellido, salario);
                }
            }  
            return emp;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algunos de los datos ingresados no son correctos","Dato incorrecto",JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }
    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        Empleado emple = getDatos();
        ControlEmpleado.ejecutarInstruccionPSQL(instruccion, emple);
        limpiarCamposIngresoEmpleados();
        jButtonEditar.setEnabled(true);
        jButtonIngresar.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        habilitarPanerEdicionEmpleado(false);
        actualizarTabla();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        instruccion = CommSQL.INSERT;
        habilitarPanerEdicionEmpleado(true);
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void llenarCampos(Empleado empleado) {
        jTextFieldUsuario.setText(empleado.getUsuario());
        jTextFieldNombre.setText(empleado.getNombre());
        jTextFieldApellido.setText(empleado.getApellido());
        jTextFieldCui.setText(empleado.getCUI());
        jTextFieldSalario.setText(String.valueOf(empleado.getSalario()));
        jTextFieldNumeroCaja.setText(String.valueOf(empleado.getNumeroCaja()));
        jTextFieldContrasena.setText(empleado.getContrasena());
    }
    
    private void habilitarPanerEdicionEmpleado(boolean habilitar) {
        jTextFieldUsuario.setEnabled(habilitar);
        jTextFieldNombre.setEnabled(habilitar);
        jTextFieldApellido.setEnabled(habilitar);
        jTextFieldCui.setEnabled(habilitar);
        jTextFieldSalario.setEnabled(habilitar);
        jTextFieldNumeroCaja.setEnabled(habilitar);
        jTextFieldContrasena.setEnabled(habilitar);
    }
    
    public Empleado getEmpleado() {
        return empleado;
    }

    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    
    private void limpiarCamposIngresoEmpleados() {
        jTextFieldUsuario.setText("");
        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldCui.setText("");
        jTextFieldSalario.setText("");
        jTextFieldNumeroCaja.setText("");
        jTextFieldContrasena.setText("");
    }

    private int getIndexRol(Rol rol) {
        for (int i = 0; i < this.listaRoles.length; i++) {
            if (listaRoles[i].name().equals(rol.name())) {
                return i;
            }
        }
        return 0;
    }
    
    private int getIndexSucursal(Sucursal sucursal) {
        for (int i = 0; i < listaSucursales.size(); i++) {
            if (listaSucursales.get(i).equals(sucursal)) {
                return i-1;
            }
        }
        return 0;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JComboBox<String> jComboBoxSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelDatosEmpleado;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldContrasena;
    private javax.swing.JTextField jTextFieldCui;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroCaja;
    private javax.swing.JTextField jTextFieldSalario;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
