

package chapinmarket.frontend.paneles;

import chapinmarket.backend.modelos.Cliente;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author CIROSS
 */
public class PanelDatosCliente extends javax.swing.JPanel {

    /** Creates new form PanelDatosCliente */
    public PanelDatosCliente() {
        initComponents();
    }
    

    public PanelDatosCliente(String titulo, String nit, String nombre, String telefono, String direccion, JLabel jLabel2JLabel, JTextField jTextField1, JTextField jTextField2, JTextField jTextField3, JTextField jTextField4) {
        this();
        this.jLabelTituloPanel.setText(titulo);
        this.jTextFieldNit.setText(nit);
        this.jTextFieldNombre.setText(nombre);
        this.jTextFieldDireccion.setText( (telefono==null) ? "" : telefono );
        this.jTextFieldDireccion.setText( (direccion==null) ? "" : direccion );
        
    }
    
    public Cliente getNuevoCliente() {
        String nit = ( (jTextFieldNit.getText().equals("")) ? "C/F" : jTextFieldNit.getText() );
        String nombre = ( (jTextFieldNombre.getText().equals("")) ? "Consumidor Final" : jTextFieldNombre.getText() );
        return new Cliente(nit,nombre);
    }
    
    public void limpiarCampos() {
        this.jLabelTituloPanel.setText("Ingresar Cliente:");
        this.jTextFieldNit.setText("");
        this.jTextFieldNombre.setText("");
        this.jTextFieldDireccion.setText("");
        this.jTextFieldDireccion.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNit = new javax.swing.JLabel();
        jLabelTituloPanel = new javax.swing.JLabel();
        jTextFieldNit = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();

        jLabelNit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNit.setText("NIT:");

        jLabelTituloPanel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTituloPanel.setText("Datos de Cliente:");

        jTextFieldNit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jTextFieldNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabelDireccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDireccion.setText("Dirección:");

        jTextFieldDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTituloPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldNit))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelTituloPanel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNit)
                    .addComponent(jTextFieldNit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelNit;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTituloPanel;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNit;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

}
